AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB table for Todo application

Resources:
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TodoItems
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  TodoTableName:
    Description: Name of the DynamoDB table
    Value: !Ref TodoTable
  TodoTableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt TodoTable.Arn
