AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Express.js backend application deployed with AWS Lambda Web Adapter

Metadata:
  AWS::ServerlessRepo::Application:
    Name: express-backend
    Description: Express.js backend application deployed with AWS Lambda Web Adapter
    Author: Serverless Web MCP Server
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
    Default: express-api
  
  Runtime:
    Type: String
    Description: Lambda runtime
    Default: nodejs18.x
    AllowedValues:
      - nodejs16.x
      - nodejs18.x
      - nodejs20.x
  
  MemorySize:
    Type: Number
    Description: Lambda memory size in MB
    Default: 512
    MinValue: 128
    MaxValue: 10240
  
  Timeout:
    Type: Number
    Description: Lambda timeout in seconds
    Default: 30
    MinValue: 3
    MaxValue: 900

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-function
      CodeUri: ./src
      Handler: app.handler
      Runtime: !Ref Runtime
      MemorySize: !Ref MemorySize
      Timeout: !Ref Timeout
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  
  FunctionName:
    Description: Lambda function name
    Value: !Ref ApiFunction
  
  FunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt ApiFunction.Arn
